--- #YAML:1.0
name: DFA-Command
version: 1.99
author:
  - Ron Savage <ron@savage.net.au>
abstract: A DFA program generator.
license: artistic
requires:
  Carp: 0
build_requires:
  Test::More: 0
  Test::Pod: 0
provides:
  DFA::Command:
    file: lib/DFA/Command.pm
    version: 1.99
  DFA::Generate:
    file: lib/DFA/Generate.pm
    version: 1.99
generated_by: Module::Build version 0.2611
